const offersList = '/offers';
const myOffers = '/offers/my-offers';
const myAcceptedOffers = '/offers/my-offers/accepted';
const offerDetails = '/offers/details/:offerId';
const editOffer = '/offers/edit/:offerId';
const newOffer = '/offers/new';
const requestsList = '/requests';
const myRequests = '/requests/my-requests';
const myAcceptedRequests = '/requests/my-requests/accepted';
const requestDetails = '/requests/details/:requestId';
const editRequest = '/requests/edit/:requestId';
const newRequest = '/requests/new';
const listaMensajes = '/messages/received';
const nuevoMensaje = '/messages/new';
const login = '/login';
const register = '/register';
const personalProfile = '/my-profile';
const editProfile = '/edit-profile';
const userProfile = '/profile/:userId';
const forgotPassword = '/forgot-password';
const resetPassword ='/reset-password/:tokenResetPassword';
const newGroup = '/groups/new';
const groupsList = '/groups';
const groupDetails = '/groups/:groupId';
const groupJoinRequests = '/groups/:groupId/joinRequests';

export { offersList, myOffers, myAcceptedOffers, offerDetails, editOffer, newOffer, requestsList, myRequests, myAcceptedRequests, requestDetails, newRequest, editRequest, listaMensajes, nuevoMensaje, login, register, personalProfile, editProfile, userProfile, forgotPassword, resetPassword, newGroup, groupsList, groupDetails, groupJoinRequests };